# intellipat tut numpy

In [1]:
import numpy as np
a=np.array([1,2,3])
b=np.array((1,2,3))
print(a)
print(b)

[1 2 3]
[1 2 3]


In [2]:
a[1]=4

In [3]:
a

array([1, 4, 3])

In [4]:
c=np.array([[1,4,5],[4,5,6]])

In [5]:
c

array([[1, 4, 5],
       [4, 5, 6]])

In [6]:
c[:0]

array([], shape=(0, 3), dtype=int32)

In [7]:
a[0:2]

array([1, 4])

In [8]:
arr=np.zeros((3,4))

In [9]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
a=np.arange(5,35,5)

In [11]:
a

array([ 5, 10, 15, 20, 25, 30])

In [12]:
a=np.linspace(5,6,10)
print(a)

[5.         5.11111111 5.22222222 5.33333333 5.44444444 5.55555556
 5.66666667 5.77777778 5.88888889 6.        ]


In [13]:
a=np.full((3,4),7)
a

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [14]:
a=np.random.random((2,5))
a

array([[0.41961612, 0.02005275, 0.61981078, 0.02609691, 0.37892924],
       [0.382678  , 0.55551096, 0.1524904 , 0.5345372 , 0.14527388]])

In [15]:
a=np.array([[2,4,5],[3.4,5,5]])
a
a.shape
a.shape=(3,2)
a

array([[2. , 4. ],
       [5. , 3.4],
       [5. , 5. ]])

In [16]:
a=np.arange(24)

In [17]:
a.size

24

In [18]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
a.ndim

1

In [20]:
a.dtype

dtype('int32')

In [23]:
a=[1,2,3]
b=[2,4,3]
np.equal(a,b)
np.array_equal(a,b)

False

In [25]:
a=np.array([1,2,3])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.std(a))
print(np.median(a))
print(np.corrcoef(a))

6
1
3
2.0
0.816496580927726
2.0
1.0


In [27]:
a=np.array([[2,34,5],[3,6,7]])
b=np.array([3,5,6])
print(a)
print(b)
print(np.sum([a,b]))
print(np.subtract(a,b))

[[ 2 34  5]
 [ 3  6  7]]
[3 5 6]
[[ 5 39 11]
 [ 6 11 13]]
[[-1 29 -1]
 [ 0  1  1]]


In [30]:
a=np.array([[1,2,3],[4,6,7],[5,7,8]])
print(a[0])
print(a[:1])
# print(a[:1,:1])

[1 2 3]
[[1 2 3]]


In [31]:
print(a[2:,:3])
#2: 2 sivay na baki na badha etle ke 3rd row
#:3 atle ke 3 sudhi na badha element

[[5 7 8]]


In [32]:
a=np.array([[1,3,4],[4,6,4]])
b=np.array([[3,4,5],[5,6,7]])
print(np.concatenate([a,b],axis=0))
print(np.concatenate([a,b],axis=1))

[[1 3 4]
 [4 6 4]
 [3 4 5]
 [5 6 7]]
[[1 3 4 3 4 5]
 [4 6 4 5 6 7]]


In [33]:
a=np.array([3,5,6])
b=np.array([5,6,7])

In [34]:
np.stack((a,b),axis=0)

array([[3, 5, 6],
       [5, 6, 7]])

In [35]:
np.stack((a,b),axis=1)

array([[3, 5],
       [5, 6],
       [6, 7]])

In [37]:
a=np.array([[2,4,5],[4,5,6]])
b=np.array([[4,6,7],[6,6,7]])
print(np.stack((a,b),axis=0))
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[[2 4 5]
  [4 5 6]]

 [[4 6 7]
  [6 6 7]]]
[[2 4 5 4 6 7]
 [4 5 6 6 6 7]]
[[2 4 5]
 [4 5 6]
 [4 6 7]
 [6 6 7]]
